/**
 * Action types.
 * @module constants/ActionTypes
 */

export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const GET_BOOKMARK = 'GET_BOOKMARK';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const PUT_BOOKMARK = 'PUT_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const GET_ALL_BOOKMARKS = 'GET_ALL_BOOKMARKS';
export const GET_ALL_VISUALIZATIONS = 'GET_ALL_VISUALIZATIONS';
export const GET_VISUALIZATION_RELATIONSHIPS =
  'GET_VISUALIZATION_RELATIONSHIPS';
export const GET_VISUALIZATION_USSAGE = 'GET_VISUALIZATION_USSAGE';
